id: P312714C1
initial_creation_type: ocr
source_metadata:
  volumes:
    c6a4932ffe694df4b93297d090b8de1f:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: ཤེས་རབ་སྙིང་པོའི་རྣམ་པར་བཤད་པ།
      total_pages: 1682
      volume_number: 56
